lib: [
  "/Users/mandalarian/Github/isomagic-todos/server/_esy/default/store/b/isomagic_todos-22f31068/install/default/lib/isomagic-todos/META" {"META"}
  "/Users/mandalarian/Github/isomagic-todos/server/_esy/default/store/b/isomagic_todos-22f31068/install/default/lib/isomagic-todos/dune-package" {"dune-package"}
  "/Users/mandalarian/Github/isomagic-todos/server/_esy/default/store/b/isomagic_todos-22f31068/install/default/lib/isomagic-todos/opam" {"opam"}
]
bin: [
  "/Users/mandalarian/Github/isomagic-todos/server/_esy/default/store/b/isomagic_todos-22f31068/install/default/bin/server" {"server"}
]
